version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=your_secure_password
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  oracle_data: